server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/do_develop?currentSchema=payment-order
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        hibernate.format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true